version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain depencies for Container Image
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"